name =  input("Restaurant name? ")
entree1 = input("First entree? ")
entree1price = input("First entree price? ")
entree2 = input("Second entree? ")
entree2price = input("Second entree price? ")
entree3 = input("Third entree? ")
entree3price = input("Third entree price? ")
restlength = len(name)
entree1length = len(entree1)
entree2length = len(entree2)
entree3length = len(entree3)
entree1pricelength = len(entree1price)
entree2pricelength = len(entree2price)
entree3pricelength = len(entree3price)
print()
print(str(1234567890123456789012345678901234567890))
print()
print (name +" Entrees")
print("-" * (restlength + 8))
print(entree1 + ("." * (36-len(entree1))) + "$" + ((" ") * (3 - entree1pricelength)) + entree1price)
print(entree2 + ("." * (36-len(entree2))) + "$" + ((" ") * (3 - entree2pricelength)) + entree2price)
print(entree3 + ("." * (36-len(entree3))) + "$" + ((" ") * (3 - entree3pricelength)) + entree3price)